### ISSUE TITLE
Misleading directions in README example

### ISSUE THREAD

**Issue by tmcclintock** [patscott/pippi#1]
The example run in the README contains essentially two commands: 
pippi pare ...
pippi example.pip

The README then states "If you want to change visual aspects of the plots... you can get away with just running script and plot **again**." It isn't clear on the first read through that "script" and "plot" were two of the running modes in example.pip until the reader then reads the next paragraph. This could perhaps be clarified.

**Comment by patscott** [comment]
Well, this _was_ stated already earlier in the README, under "Usage", but I've amended the passage you refer to anyway to make it crystal clear.  Thanks for your interest, anyway.

**Comment by tmcclintock** [comment]
That's fair. I had read the paper then came to the repo and jumped to the examples section. I guess I should have read the whole thing :-P.
